{% set name = "construct-typing" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/construct-typing-{{ version }}.tar.gz
  sha256: 26da1ed7383c5dfe7f38a43c6281ad06bce2059bf02d5a0d2cc3c0e52632c0bd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - construct ==2.10.67
    - python >={{ python_min }}

test:
  imports:
    - construct_typed
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/timrid/construct-typing
  summary: Extension for the python package 'construct' that adds typing features
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kevinheavey
